# Generated by Django 4.2.7 on 2025-07-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_department_remove_student_major_student_depaerment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='depaerment',
            new_name='department',
        ),
    ]
