# Generated by Django 4.2.7 on 2025-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_level_student_semester_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceencoding',
            name='detection_status',
            field=models.CharField(choices=[('success', 'Success'), ('no_face', 'No Face Detected'), ('error', 'Error')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='faceencoding',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faceencoding',
            name='encoding_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
